name: Manual website deployment

on:
  workflow_dispatch:

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy Workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: 'deploy.yml'  # Replace with the name of the workflow file you want to trigger
          ref: 'website'  # Replace with the branch or ref of the workflow file
          inputs: |
            triggerUser: ${{ github.actor }}
