name: Manual website deployment

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy Workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: deploy.yml  # Replace with your actual workflow ID
          ref: website  # Replace with your target branch or ref
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: |
            triggerUser=${{ github.actor }}
