name: test triggering workflow

run-name: test deploy

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          payload='{
            "ref": "website",
            "inputs": {
              "triggerUser": "${{ github.actor }}"
            }
          }'
          echo "$payload" > payload.json
          
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            --data @payload.json \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy.yml/dispatches
