name: Manual website deployment

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Call Deploy Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const triggerUser = '${{ github.actor }}';

              // Import Octokit from @octokit/rest
              const { Octokit } = require('@octokit/rest');

              const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

              // Use await inside an async function
              const response = await octokit.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'deploy.yml',  // Replace with your actual workflow ID
                ref: 'website',  // Replace with your target branch or ref
                inputs: {
                  triggerUser: triggerUser,
                },
              });

              console.log(response.data);
            } catch (error) {
              console.error('Error:', error);
              throw error;
            }
