name: Manual website deployment

run-name: Trigger website deployment to GitHub Pages

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call Deploy Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const triggerUser = '${{ github.actor }}';
            
            const github = require('@actions/github');
            const octokit = new github.GitHub(process.env.GITHUB_TOKEN);
            const context = github.context;

            const response = await octokit.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy.yml',
              ref: 'website',
              inputs: {
                triggerUser: triggerUser,
              },
            });
            
            console.log(response);
