# Manual website deployment workflow
name: Manual website deployment

on:
  workflow_dispatch:
    inputs:
      triggerUser:
        description: 'User who triggered the deployment'
        required: true

permissions:
  actions: write
  contents: write

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRIGGER_USER: ${{ github.actor }}
        run: |
          # Construct payload for the workflow dispatch event
          payload="{\"ref\":\"website\",\"inputs\":{\"triggerUser\":\"${TRIGGER_USER}\"}}"

          # Trigger the deploy workflow using GitHub API
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy.yml/dispatches \
            -d "$payload"
