name: Manual website deployment

run-name: Trigger website deployment to GitHub Pages

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Force-deploy website to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy.yml/dispatches \
            -d '{"ref":"website"}'
